[alias]
today = "run --quiet --release --features today -- today"
scaffold = "run --quiet --release -- scaffold"
download = "run --quiet --release -- download"
read = "run --quiet --release -- read"

solve = "run --quiet --release -- solve"
all = "run --quiet --release -- all"
time = "run --quiet --release -- time"

[env]
AOC_YEAR = "2025"
ADVENT_OF_CODE_SESSION = "53616c7465645f5f1a68399619f369f63a8f5c6bc2f50eba75c0512b99466d3086759c1a16ce1de9442d0db07da7a1e12de474d00345f5c7823065992b6ef3b8"
